export default function Shop() {
  <div className="flex flex-col items-center">
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
  </div>
}