import Hero from "~/components/customer/hero";
import { Button } from "~/components/ui/button";

export default function BuyerIndexPage() {
  return (
  <main className="w-full h-fit flex flex-col items-center">
    <Hero />
    <div className="dark:bg-black w-full h-[5000px] flex flex-col items-center p-12 p-6">
      <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    <h2>THIS SECTION IS FOR THE CUSTOMER SHOP</h2>
    </div>
  </main>
  );
}